on:
  push:
    branches:
      - main

name: Deploy to production
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update CloudFront Distribution
      run: sed -i "s/CLOUDFRONT_ID/${{ secrets.CLOUDFRONT }}/g" config.yaml
    - name: Update LinkedIn Link
      run: sed -i "s/LINKEDIN_LINK/${{ secrets.LINKEDIN }}/g" config.yaml
    - name: Build
      run: hugo --gc -DEF --baseURL="https://daniels.dev"
    - name: Deploy to S3
      run: hugo deploy --maxDeletes -1 --invalidateCDN --target daniels-dev --logLevel info